### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by ghost** [Asbatel/ContainerHIDS#2]
Thank you for your great work. I'm wondering which version of LID-DS you used. I noticed that LID-DS 2019 has a .csv file to tell whether a record is normal and LID-DS 2021 separates the dataset into training, testing and validation. I suppose that if I use the 2021 dataset I shall just use the records in the training folder as it contains only normal data, and if I use the 2019 dataset I would need to manually pick out the normal records for training.
Another question is that I find in the CB-DS dataset 1000 scap files for normal record and 100 or 101 scap files for each attack, while the paper says 1700 for normal and 99 for each attack. I wonder what made the difference.
I'd appreciate it if you could answer my confusion😊.

**Comment by ghost** [comment]
I used CB-DS to get training elements, and got the BrokenPipeError. I tried to reduce the number of worker processes to 4 by manually specifying `processes=4` but it didn't work. The error traceback is as follows, do you have any idea?😢

~/ContainerHIDS/chids/tools# Process ForkPoolWorker-6:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by Asbatel** [comment]
1) The CB-DS dataset has been updated ;)
2) For LID-DS, I utilized the previous version that consisted of 1000 benign samples and 99 attack samples. During the evaluation process, I conducted 4-fold cross-validation using a 25:75 train-test split of normal scaps and 99 attack scaps as test data.

To obtain information about the new structure, I recommend contacting the dataset authors.
